name: "Web App Deployment for Linux Containers"
on:
  push:
    branches: 
      - master
    paths:
    - 'AppServiceDemo/**'
    - '.github/workflows/container_deploy.yml'

env:
    RELEASE_DEST: appservicedemo
    APP_NAME: app-service-demo-containers-jaspecla
    LUNCH_SPECIAL: 'Pigs in a Blanket'
    REGISTRY_NAME: 'appservicedemocontainersjaspecla'
    CONTAINER_TAG: 'aspnetdemoapp'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # checkout the repo
    - uses: actions/checkout@master
    
    # authenticate to Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_CONTAINER }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build ./AppServiceDemo -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.CONTAINER_TAG }}:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.CONTAINER_TAG }}:${{ github.sha }}

    - name: "Set App Service Settings"
      uses: azure/appservice-settings@v1
      with:
        app-name: '${{ env.APP_NAME }}'
        slot-name: 'dev'
        app-settings-json: >-
          [{"name": "LunchSpecial", "value": "${{ env.LUNCH_SPECIAL }}", "slotSetting": false},
          {"name": "DOCKER_REGISTRY_SERVER_URL", "value": "${{ env.REGISTRY_NAME }}.azurecr.io", "slotSetting": false},
          {"name": "DOCKER_REGISTRY_SERVER_USERNAME", "value": "${{ secrets.REGISTRY_USERNAME }}", "slotSetting": false},
          {"name": "DOCKER_REGISTRY_SERVER_PASSWORD", "value": "${{ secrets.REGISTRY_PASSWORD }}", "slotSetting": false}]
      id: settings

    - uses: azure/webapps-deploy@v2
      with:
        app-name: '${{ env.APP_NAME }}'
        slot-name: 'dev'
        images: '${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.CONTAINER_TAG }}:${{ github.sha }}'

